name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
          cache-dependency-path: ./go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
          cache-dependency-path: ./go.mod
      - name: Run gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          find . -name '*.go' | grep -v pb | xargs gofumpt -l -w
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --issues-exit-code=0 --timeout=5m